[package]
name = "instrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
instrs-core = { path = "../instrs-core" }
instrs-derive = { path = "../instrs-derive" }
